Feat/archive db
anniversaryArchive/archive-back pull request #16
Opened 2022-07-16 15:27 UTC by bongguma

## 🛠 주요 변경 사항 
해당 PR에서 주요 변경 사항에 대하여 작성해주세요.

- archive model 설계
- archive query / mutation 구현

<br/>

## 👩‍💻 Code Review 
Reviewer가 Code Review 시 중점적으로 봐야할 부분을 작성해주세요.

- archive query 안에 필요한 데이터가 다 들어갔는지 또 필요한 데이터가 무엇이 있을지 같이 고민부탁드립니다 ..:) ( 저는 카카오 지도를 참고했습니다.)
- apolloServer 안에서 query / mutation이 잘 실행하는지 확인 부탁드립니다! 

<br/>

## 👨‍💻 Design Review 
Reviewer가 Design Review 시 중점적으로 봐야할 부분을 작성해주세요.

<br/>

## 📸 스크린샷
작업한 화면의 스크린샷을 첨부해주세요. (이미지 혹은 .gif)
<img width="1322" alt="스크린샷 2022-07-17 오전 12 26 43" src="https://user-images.githubusercontent.com/75101488/179361338-945df858-65e9-4851-9bba-daad30da5ecb.png">

<br/>

## ✅ Test Checklist 

- [ ] Archvie query 확인
- [ ] Archvie mutation 확인

<br/>

## 🙏 To Reviewers 
- 흥미를 느끼고 있지만 어려운 부분이 많네요! 고쳐야할 부분이 있다거나 의견이 있으시다면 언제든 환영입니다 - :)

2022-07-16 16:17 UTC, hyejin-1010 requested changes
수고하셨습니다!! 🙇‍♀️
보이는 부분 몇 개랑 Archive DB에 대한 의견 코멘트로 남겨두었습니다 😊

2022-07-16 16:17 UTC, hyejin-1010 commented on models/archive.js
> +    link: String,                                   // 아카이브 대표링크
일단 지금 당장 생각나는 건 아래 필드들입니다 ! 
아래 필드들은 필요하지 않을까용?? 🤔

- 위도/경도(lat, lng)
- 주최자 트위터 아이디 (organizer?
- 영업시간 (start_time, end_time? 
- 이미지 리스트, 포스트와 같은 것들을 담아둘 (Images)
- 기본 특전 (Array<String> basic perks ?.. 
- 디저트(세트) 특전 (Array<String> special perks ?..
- 선착순 특전 (Array<{ Datetime date, String item, int count}> fcfs perks ?..
- 해시태그 이벤트 (String hashtag_event
- 럭키드로우 (lucky_draw, { DateTime startDate, DateTime endDate, startTime, endTime, List<String> itemOfRank ..

2022-07-16 16:17 UTC, hyejin-1010 commented on config/db-config.json
> +{
엇 이 파일은 잘 못 올리신 거 같습니다! 삭제해주세요! 🙇‍♀️

2022-07-16 16:17 UTC, hyejin-1010 commented on routes/archive.js
> +const Archive = require('../models/archive');
현재 저희가 GraphQL 위주로 사용하기 있는데, Restful 도 같이 구현하신 특별한 이유가 혹시 있으실까용??

2022-07-16 16:17 UTC, hyejin-1010 commented on routes/archive.js
> +    res.json({ success: true, archvie });
`{ success: true, data: archvie }` 이게 더 맞을 것 같습니다 !!

2022-07-17 03:02 UTC, bongguma commented on config/db-config.json
> +{
`db-config.json` 삭제했습니다!

2022-07-17 03:16 UTC, bongguma commented on models/archive.js
> +    link: String,                                   // 아카이브 대표링크
위도와 경도는 추가를 해두었습니다! 영업시간과 이미지리스트, 주최자 트위터 아이디는 추가해두겠습니다! 제가 아이돌 카페에 초점을 맞춘다는 것을 까먹고 특전과 관련한 부분은 생각하지 못 했던 것 같습니다 ㅠ 특전 같은 경우에는 archvie 안에 포함되는 것이 아닌 특전모델과 특전 insert, update, remove 등 뮤테이션이 구현해 아카이브와 관계를 이뤄져야한다고 생각합니다! 이 부분을 월요일 회의에 의견을 구하려했는데 .. 특전 관련 제외한 나머지 필드만 추가하는 방향으로 진행하는건 어떨까요?

2022-07-17 03:31 UTC, bongguma commented on routes/archive.js
> +const Archive = require('../models/archive');
나중에 쓸 일이 있지 않을까 .. 하고 restful api도 만들어보았는데 ... 헷갈릴 수 있으니 삭제해두겠습니당 ..:)

2022-07-18 01:38 UTC, hyejin-1010 commented on models/archive.js
> +    link: String,                                   // 아카이브 대표링크
좋습니다 !! 특전 관련은 회의 후에 작업하시죠!!

2022-07-18 01:41 UTC, hyejin-1010 reviewed
수고하셨습니다! 🙇‍♀️ 몇 개 Comment 만 남겼습니다!

2022-07-18 01:41 UTC, hyejin-1010 commented on models/archive.js
> +    imsges: [mongoose.Types.ObjectId],              // 아카이브 이미지리스트
이거 오타인 거 같습니다! `images`로 수정해주세요!

2022-07-18 01:41 UTC, hyejin-1010 commented on models/archive.js
> +    number: String,                                 // 아카이브 전화번호
`number`는 전화번호라는 느낌이 잘 안 나는 거 같아서, `tel` 혹은 `phoneNumber` 로 변경하면 어떨까요??

2022-07-18 02:29 UTC, bongguma commented on models/archive.js
> +    imsges: [mongoose.Types.ObjectId],              // 아카이브 이미지리스트
앗 ..!!!!! 넵!! 저녁에 수정해서 다시 PR 올리겠습니다 :)

2022-07-18 02:30 UTC, bongguma commented on models/archive.js
> +    number: String,                                 // 아카이브 전화번호
아! 그렇네요..! 뭔가 필드명이 명확하지 않군요 ..!!! phoneNumber가 더 직관적일 거 같네요!!!

2022-07-18 11:47 UTC, bongguma commented on models/archive.js
> +    number: String,                                 // 아카이브 전화번호
images 오타 & number 필드명 수정 했습니다!!

2022-07-18 14:02 UTC, hyejin-1010 reviewed
수고하셨습니다🙇‍♀️ 다시 코드를 보니 생각나는 Comment가 생겨서 몇 개 달아두었습니다!!

2022-07-18 14:02 UTC, hyejin-1010 commented on models/archive.js
> +    likeCount: { type: Number, default: 0 },        // 좋아요갯수
좋아요 개수에 대해서 생각을 해보니까, 어떤 유저가 어떤 아카이브를 좋아요를 눌렀는 지도 알아야 하니까, Archive.likeCount가 아니라 `Like { user: ObjectId, archive: ObjectId }` 이런 느낌으로 좋아요를 기록하는 Collection이 있고, resolve에서 likeCount는 `Like.find({ archive: _._id })` 이런 느낌으로 return 하게 해두는 게 맞지 않을까용 ??

2022-07-18 14:02 UTC, hyejin-1010 commented on models/archive.js
> +    reviewCount: { type: Number, default: 0 },      // 리뷰갯수
현재 1.0에서 리뷰 기능 계획이 없고, 추후에 리뷰 기능이 생긴다고 하더라도 리뷰 DB를 따로 생성해야 할 거 같아서 일단 현재로서는 해당 필드는 빼는 게 어떨까용 ??

2022-07-19 23:20 UTC, bongguma commented on models/archive.js
> +    reviewCount: { type: Number, default: 0 },      // 리뷰갯수
카카오지도 레퍼런스로 참고하면서 안에 리뷰 갯수를 보여주고 있어 저도 추가해줬었습니다 ! 말씀처럼 당장 리뷰계획은 없으므로 수정해두겠습니다!

2022-07-20 05:47 UTC, bongguma commented on models/archive.js
> +    likeCount: { type: Number, default: 0 },        // 좋아요갯수
이 부분은 user 모델 쪽에 user가 누른 좋아요 아카이브 리스트 설계한 이후 추가 작업을 진행하려고 해서 일단 likeCount만 넣어둔 상태였습니다 ..! '좋아요'를 기록하는 컬렉션이라는 말이 'like'에 대한 스키마가 있어야한다는 말씀이실까요?

2022-07-20 05:47 UTC, bongguma commented on models/archive.js
> +    reviewCount: { type: Number, default: 0 },      // 리뷰갯수
reviewCount는 삭제해두었습니다!

2022-07-20 06:43 UTC, hyejin-1010 commented on models/archive.js
> +    likeCount: { type: Number, default: 0 },        // 좋아요갯수
네네 like에 대한 스키마가 있어야 한다는 의미이긴 한데, 이번에 작업해달라는 의미는 아닙니다!
제가 말씀드린 이유는 추후에 좋아요 아카이브 리스트가 설계된다고 했을 때 archive의 likeCount가 DB에 저장되지는 않게 될 거 같아서 말씀드린 것입니다! model schema에 넣어놓으면, DB에 저장된다는 의미니까요!
임의로 넣어두려면 graphql schema에만 넣어놓고, 추후에 resolve에서 작업을 해주면 되지 않을까요??

2022-07-20 06:57 UTC, bongguma commented on models/archive.js
> +    likeCount: { type: Number, default: 0 },        // 좋아요갯수
'archive의 likeCount가 DB에 저장되지는 않게 될 거 같아서 말씀드린 것입니다!' &rarr; 이 말씀은 아카이브 디비 안에 likeCount가 저장이 되지 않는다는 말씀이 맞으신가요? 제가 likeCount를 넣으려고 했던 이유는 이 아카이브를 좋아하는 유저가 몇명이 되는지 확인하기 위해 필요하다고 생각해 필드를 추가해주었는데 ... 좋아요 아카이브 리스트 따로 아카이브 안에 likeCount 따로 들고 가는 게 맞지 않나요  ?

2022-07-20 07:51 UTC, hyejin-1010 approved these changes
LGFM 💖

2022-07-21 01:56 UTC, chochozabe approved these changes
수고하셨습니다 ~!

2022-07-23 07:28 UTC, kimsojung318 approved these changes
고생하셨습니다!

2022-07-23 14:06 UTC, merged