graphql & mongodb 연결
anniversaryArchive/archive-back pull request #6
Opened 2022-07-03 08:19 UTC by bongguma

## 🛠 주요 변경 사항 
1. `app.js` 안에 있던 mongodb 연결 부분을 `mongodb.js` 파일로 분리
2. `nodemon` 도구를 사용해 로직 저장 시 자동으로 재시작하게 수정
3. graphql & mongodb 세팅해 `groups` 데이터 확인할 수 있게 추가

<br/>

## 👩‍💻 Code Review 
Reviewer가 Code Review 시 중점적으로 봐야할 부분을 작성해주세요.

1. `app.js` 안에 있던 mongdb 연결 부분을 `mongodb.js` 파일로 분리했는데 많이 분리하는지 궁금합니다.
2.  Query 안 `Artists` 타입을 `[Artist]`로 지정해주려했는데 아직 Artist model을 생성하지 않아 `[String]` 타입으로 작업해두었습니다 ..:( 추후 Artist model을 생성하시는 분이 계시거나 제가 생성하면 수정해두겠습니다!
3. schema/schema와 resolvers/resolver 폴더명과 파일명이 괜찮은지 확인 및 수정되어야하는 로직부분이 있는지 확인부탁드립니다.

<br/>

## ✅ Test Checklist 
- [ ] apolloServer로 groups 쿼리를 잘 불러오는 지 확인

<br/>

## 🙏 To Reviewers 
node.js를 처음 써봐서 미숙합니다 :( 부족한 부분이나 수정되어야할 부분이 있으면 언제든지 말씀해주세요!
파일명과 폴더명도 더 좋은 네이밍이 있으면 말씀해주세요!

2022-07-03 10:15 UTC, hyejin-1010 requested changes
수고하셨습니다! 몇가지 코멘트들을 남겨두었습니다! 🙇‍♀️
몇개는 그냥 의견일 뿐이라서 확인하시고 그냥 넘기셔도 됩니다!! 😊

2022-07-03 10:15 UTC, hyejin-1010 commented on Schema/schema.js
> +
해당 파일명은 schema/index.js 가 더 맞지 않을까라는 생각이 드네요🤔 `const typeDefs = require('./schema')` 이렇게 호출할 수 있게요! 
나중에 schema를 여러 파일로 분리한다고 해도 기본이 되는 파일이라는 게 직관적으로 보이는 것도 index.js가 아닐까 싶은데 어떻게 생각하시나용 ?!

2022-07-03 10:15 UTC, hyejin-1010 commented on mongodb/mongodb.js
> +const express = require('express');
해당 코드 내에서 express는 사용하지 않던데 지워주세용🙇‍♀️

2022-07-03 10:15 UTC, hyejin-1010 commented on package.json
> +    "dotenv": "16.0.1",
제가 지금 코드를 확인해 봤을 때 `dotenv`을 사용하는 부분이 없는 거 같은데 맞을까요?? 👀

2022-07-03 10:15 UTC, hyejin-1010 commented on resolvers/resolver.js
> +const Group = require('../models/group');
`schema/schema.js`에 달은 코멘트와 같은 논리로 `resolvers/index.js` 형식이 더 좋지 않을까 하는 생각이 드네용 ! 🤔

2022-07-03 10:15 UTC, hyejin-1010 commented on Schema/schema.js
> +    _id: ID
`name: String` 도 추가되어야 할 거 같아요!! 👀

2022-07-03 12:01 UTC, bongguma commented on package.json
> +    "dotenv": "16.0.1",
아 넵! 처음에 테스트할 때 사용하다 현재에는 `dotenv`관련 로직을 삭제했습니다. package도 삭제 진행하겠습니다!

2022-07-03 12:03 UTC, bongguma commented on Schema/schema.js
> +    _id: ID
아! name도 있네요 🤣

2022-07-03 12:10 UTC, bongguma commented on Schema/schema.js
> +
파일명을 index.js로 하면 require가 폴더명까지 입력해서 호출할 수 있군요! 예제를 참고했을 때 또한 index.js 로 표현하더라구요..! index.js로 파일명을 수정하도록 하겠습니다!

2022-07-03 12:39 UTC, hyejin-1010 reviewed
수고하셨습니당! mongodb.js에 comment 하나 남겼습니다 🙇‍♀️

2022-07-03 12:39 UTC, hyejin-1010 commented on mongodb/mongodb.js
> +const express = require('express');
으음,, mongdodb.js에서는 `const express = require('express');`와 같이 express를 정의해놓고 사용하지 않던데 추후 사용할 예정이라 안 지우시는 것일까용??

2022-07-03 12:47 UTC, bongguma commented on mongodb/mongodb.js
> +const express = require('express');
아앗 .. 제가 봤다고 표시만 하고 ...다른 커밋하고 까먹어버렸네요 ...🥲

2022-07-03 12:50 UTC, hyejin-1010 approved these changes
LGTM 👍🏻

2022-07-03 13:07 UTC, kimsojung318 reviewed
저도 간단한 리액트 프로젝트 mongodb 연결했을 때 따로 분리해서 사용했었습니다.
Schema/Resolver 폴더/파일명 좋습니다!

2022-07-04 13:19 UTC, kimsojung318 approved these changes
다시 확인했습니다!

2022-07-04 14:43 UTC, chochozabe commented
수고하셨습니다🍠🍠🍠

2022-07-04 14:44 UTC, merged

2022-07-04 14:44 UTC, chochozabe approved these changes